export const pizzaData: Food[] = [
	{
		type: "fruit",
		name: "Tomato",
		eaten: "cooked and raw",
		component: "whole",
	},
	{
		type: "fruit",
		name: "Bell Pepper",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "fruit",
		name: "Pineapple",
		eaten: "raw",
		component: "meat",
	},
	{
		type: "fruit",
		name: "Olives",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "fruit",
		name: "Mushrooms",
		eaten: "cooked",
		component: "whole",
	},
	{
		type: "fruit",
		name: "Onions",
		eaten: "cooked",
		component: "topping",
	},
	{
		type: "fruit",
		name: "Jalapenos",
		eaten: "raw",
		component: "topping",
	},
	{
		type: "fruit",
		name: "Banana Peppers",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "vegetable",
		name: "Spinach",
		eaten: "cooked",
		component: "leaf",
	},
	{
		type: "vegetable",
		name: "Broccoli",
		eaten: "cooked",
		component: "flower",
	},
	{
		type: "vegetable",
		name: "Zucchini",
		eaten: "cooked",
		component: "root",
	},
	{
		type: "fruit",
		name: "Tomato",
		eaten: "raw",
		component: "fruit",
	},
	{
		type: "vegetable",
		name: "Mushrooms",
		eaten: "cooked",
		component: "top",
	},
	{
		type: "vegetable",
		name: "Onions",
		eaten: "cooked",
		component: "bulb",
	},
	{
		type: "fruit",
		name: "Apple",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "fruit",
		name: "Orange",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "fruit",
		name: "Grapes",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "vegetable",
		name: "Carrot",
		eaten: "raw",
		component: "root",
	},
	{
		type: "vegetable",
		name: "Cabbage",
		eaten: "cooked",
		component: "leaf",
	},
	{
		type: "vegetable",
		name: "Potato",
		eaten: "cooked",
		component: "root",
	},
	{
		type: "fruit",
		name: "Strawberry",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "fruit",
		name: "Watermelon",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "vegetable",
		name: "Cucumber",
		eaten: "raw",
		component: "whole",
	},
	{
		type: "vegetable",
		name: "Eggplant",
		eaten: "cooked",
		component: "whole",
	},
];
